#Avoid tmpfs controlled mounts entirely
ENROOT_RUNTIME_PATH /run/user/${UID}/enroot/runtime/
ENROOT_CACHE_PATH /run/user/${UID}/enroot/cache/
ENROOT_DATA_PATH /run/user/${UID}/enroot/data/
ENROOT_TEMP_PATH /run/user/${UID}/enroot/tmp/
